name: 'PR Size Labeler'
description: 'Add labels to new pull requests based on the size of the changes'
author: 'GitHub & Julio Castillo'
inputs: 
  repo-token:
    description: 'The GITHUB_TOKEN secret'
  configuration-path:
    description: 'The path for the label configurations'
    default: '.github/pr-size-labeler.yml'
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'
